### ISSUE TITLE
[BUG] getVtuber/:id api can not show

### ISSUE THREAD

**Issue by Nek0Lex** [Code4Cat/csci4140_project_server#1]
Reproduce:
The `/vtubers/:id` API can not display the correct information.

Solution:
In the `const getVtuber` controller method, replace `res.status(200).json(Vtuber);` to lower letter "vtuber"  `res.status(200).json(vtuber);`:

![image](https://user-images.githubusercontent.com/32164846/116811349-6f34f200-ab7b-11eb-9800-988fda768903.png)

**Comment by Code4Cat** [comment]
It's now fixed. Thank you.
